// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'dart:io' show Platform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } else if (Platform.isAndroid) {
      return android;
    } else if (Platform.isIOS) {
      return ios;
    } else if (Platform.isLinux) {
      return linux;
    } else if (Platform.isMacOS) {
      return macos;
    } else if (Platform.isWindows) {
      return windows;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWCO3AaWWdjwYMqqLkr0GlyuD4588LAaU',
    appId: '1:695708079946:web:cad363e51c21651c5d53b3',
    messagingSenderId: '695708079946',
    projectId: 'vtu-app-85514',
    authDomain: 'vtu-app-85514.firebaseapp.com',
    storageBucket: 'vtu-app-85514.firebasestorage.app',
    measurementId: 'G-3MC47SWN60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjYi2v2Dg7O0JgJZip_0XaG4GlzKLJBZU',
    appId: '1:695708079946:android:0eacaa7462ac393d5d53b3',
    messagingSenderId: '695708079946',
    projectId: 'vtu-app-85514',
    storageBucket: 'vtu-app-85514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA0Iu8FcQZCWdrHnu8o84F9tnOr9trpX4',
    appId: '1:695708079946:ios:4dfdbfe3b01345155d53b3',
    messagingSenderId: '695708079946',
    projectId: 'vtu-app-85514',
    storageBucket: 'vtu-app-85514.firebasestorage.app',
    iosClientId: '695708079946-s3i2134s6kbqve4jm96mf47346drhttu.apps.googleusercontent.com',
    iosBundleId: 'com.yourcompany.vtuApp',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA0Iu8FcQZCWdrHnu8o84F9tnOr9trpX4',
    appId: '1:695708079946:ios:4dfdbfe3b01345155d53b3',
    messagingSenderId: '695708079946',
    projectId: 'vtu-app-85514',
    storageBucket: 'vtu-app-85514.firebasestorage.app',
    iosClientId: '695708079946-s3i2134s6kbqve4jm96mf47346drhttu.apps.googleusercontent.com',
    iosBundleId: 'com.yourcompany.vtuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWCO3AaWWdjwYMqqLkr0GlyuD4588LAaU',
    appId: '1:695708079946:web:2edaa83dcf39d9fd5d53b3',
    messagingSenderId: '695708079946',
    projectId: 'vtu-app-85514',
    authDomain: 'vtu-app-85514.firebaseapp.com',
    storageBucket: 'vtu-app-85514.firebasestorage.app',
    measurementId: 'G-BFPFHKR8QV',
  );

}